config/routes.rb
Rails.application.routes.draw do
  #customer
  root to: "customers/homes#top"
  get 'about' => 'customers/homes#about'
  get '/customers/contact' => 'customers/customers#contact'

  devise_for :customers, :controllers => {:sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
  }
  scope module: :customers do
    resources :items,only:[:index, :show]
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'
    resource :customers,only:[:edit, :update, :show] do
      collection do
        get 'quit'
        patch 'out'
      end
    end

    resources :cart_items, only:[:index, :update, :create, :destroy] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
    resources :orders, only:[:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  #admin
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  get "/admin" => "admin/homes#index"

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :new, :create, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update] do
      member do
        get :current_index
        resource :order_details, only:[:update]
      end
      collection do
        get :today_order_index
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :phone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :email, uniqueness: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    validates :customer_id, :address, :name, :shipping_cost,
              :total_payment, :payment_method, presence: true
    validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
    validates :shipping_cost, :total_payment, numericality: { only_integer: true }

    enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
    enum status: {"入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中": 3, "発送済み": 4}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "顧客情報を更新しました"
      redirect_to admin_customer_path
    else
      render "edit"
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :kana_first_name, :phone_number, :postal_code, :address, :email, :is_deleted)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page]).per(10)
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    flash[:notice] = "注文ステータスを変更しました"
    redirect_to admin_order_path(@order)
      if @order.status == "入金確認"
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 1)
        end
      end
  end
  
  def today_order_index
  end

  def current_index
  end
  
  private
  def order_params
    params.require(:order).permit(:shipping_cost, :total_payment, :name, :payment_method, :address, :postal_code, :status, :making_status)
  end
  
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
  before_action :authenticate_customer!

  def index
    @addresses = current_customer.addresses
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = current_customer.addresses
    if @address.save
      flash.now[:notice] = "新規配送先を登録しました"
      redirect_to addresses_path
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    @addresses = current_customer.addresses
    flash.now[:alert] = "配送先を削除しました"
    redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      flash[:success] = "配送先を変更しました"
      redirect_to addresses_path
    else
      render :edit
    end
  end

private

  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = CartItem.where(customer_id:current_customer)
  end

  def create
    @cart_item = CartItem.new(cart_items_params)
    @cart_item.customer_id = current_customer.id
    @old_cart_item = CartItem.find_by(item: @cart_item.item)
    if @old_cart_item.present? and @cart_item.valid?
      @cart_item.count += @old_cart_item.count
      @old_cart_item.destroy
    end
    if @cart_item.save
      redirect_to cart_items_path
    else
      render ('items/show')
    end
  end

  def update
    @cart_item = CartItem.find(params["id"])
    @cart_item.update(count: params[:cart_item][:count].to_i)
    @cart_item.save
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params["id"])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path
  end


private

  def cart_items_params
    params.require(:cart_item).permit(:customer_id, :item_id, :count)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end
  def edit
    @customer = current_customer
  end
  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render :edit
    end
  end
  def quit
  end
  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end
  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :phone_number, :email, :postal_code, :address)
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController

  def top
    @items = Item.all
    @genres = Genre.all
  end

  def about
  end


end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

  def index
    @total_items = Item.all
    @items = Item.all.page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  private

  def items_params
    params.require(:item).permit(:genre_id, :name, :price, :is_active, :image_id)
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def new
    @order = Order.new
    @addresses = current_customer.addresses
  end

  def confirm
    @cart_items = current_customer.cart_items

    @order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method])

    # total_paymentに請求額を入れる billingはhelperで定義
    @order.total_payment = billing(@order)

    # my_addressに1が入っていれば（自宅）
    if params[:order][:my_address] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = full_name(current_customer)

    # my_addressに2が入っていれば（配送先一覧）
    elsif params[:order][:my_address] == "2"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address = ship.address
      @order.name = ship.name

    # my_addressに3が入っていれば(新配送先)
    elsif params[:order][:my_address] == "3"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
      @ship = "1"

    # 有効かどうかの確認
      unless @order.valid? == true
        @addresses = Address.where(customer: current_customer)
        render :new
      end
    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    @order.save

    # 情報入力に新規配送先があれば保存
    if params[:order][:ship] =="1"
      current_customer.address.create(address_params)
    end

       # カート商品の情報を注文履歴に移動させる
    @cart_items = current_customer.cart_items
    @cart_items.each do |cart_item|
      @order_detail = OrderDetail.new
      @order_detail.item_id = cart_item.item_id
      @order_detail.order_id = @order.id
      @order_detail.count = cart_item.count
      @order_detail.price = cart_item.item.price * cart_item.count 
      @order_detail.save
      end
    # 最後にカートを全て削除する
    @cart_items.destroy_all

    redirect_to thanx_orders_path
  end

  def thanx
  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_payment)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:alert] = "必須項目を入力してください"
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper

  def subtotal(cart_item)
    cart_item.item.tax_in_price * cart_item.count
  end

  def total_price(cart_items)
    total_price = 0
    cart_items.each do |cart_item|
      total_price += subtotal(cart_item)
    end
    return total_price
  end

end

app/views/customers/orders/confirm.html.erb
<div class="container">
  <h2 class="my-5">注文情報確認</h2>
  <div class="row">
    <div class="col-xs-9">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |cart| %>
          <tr>
            <td class="text-left">
              <%= cart.item.name %>
            </td>
            <td class="text-right">
              ¥<%= cart.item.tax_in_price.to_s(:delimited) %>
            </td>
            <td class="text-right">
              <%= cart.count %>
            </td>
            <td class="text-right">
              ¥<%= sub_price(cart).to_s(:delimited) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

     <div class="col-xs-3 offset-md-1">
      <table class="table">
        <tr>
          <th>送料</th>
          <td class="text-right">¥<%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <th>商品合計</th>
          <td class="text-right">¥<%= total_price(@cart_items).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>請求金額</th>
          <td class="text-right">¥<%= billing(@order).to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-8">
      <table class="table">
        <thead>
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= @order.payment_method %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= "#{@order.postal_code} #{@order.address} #{@order.name}" %>
          </td>
        </tr>
        </thead>

      </table>
    </div>
  </div>

  <div class="row">
    <h3 class="mx-auto">
      <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
      <%= f.hidden_field :payment_method %>
      <%= f.hidden_field :postal_code %>
      <%= f.hidden_field :address %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :total_payment %>
      <%= f.submit '注文を確定する', class: 'btn btn-success' %>
      <% end %>
    </h3>
  </div>
</div>

app/views/customers/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>
<div class="row">
  <div class="col-xs-12">
    <h2>注文履歴一覧</h2>
    <% if @orders.present? %>
    <table class="table table-hover table-bordered table-condensed">
      <thead>
        <tr>
          <th><i class="fas fa-calender-day"></i>注文日</th>
          <th>配送先</th>
          <th>注文商品</th>
          <th>支払い金額</th>
          <th>ステータス</th>
          <th>注文詳細</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
          <td>
            <%= order.postal_code %><br>
            <%= order.address %><br>
            <%= order.name %>
          </td>
          <td>
            <% order.order_details.each do |order_detail| %>
            <%= order_detail.item.name %><br>
            <% end %>
          </td>
          <td><%= order.total_payment.to_s(:delimited) %>円</td>
          <td><%= order.status %></td>
          <td>
            <%= link_to "注文詳細", order_path(order), class: "btn btn-success" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <p>注文履歴がありません</p>
    <% end %>
  </div>
</div>

app/views/customers/orders/new.html.erb
<div class="container">
  <h2 class="font-weight-bold my-5">注文情報入力</h2>
  <div class="row">

    <div class="col-xs-12">
      <% if current_customer.cart_items.present? %>
        <div class="col-xs-offset-1">
        <%= form_with model: @order, url: confirm_orders_path, method: :post, local: true do |f| %>
          <h5 class="col-xs-3 font-weight-bold mb-3">支払い方法</h5>
           <div class="col-xs-10">
             <%= f.radio_button :payment_method, :"クレジットカード", checked: true %>
             <%= f.label :"クレジットカード"%>
           </div>
           <div class="col-xs-10">
             <%= f.radio_button :payment_method, :"銀行振込" %>
             <%= f.label :"銀行振込"%>
           </div>

          <h5 class="col-xs-3 font-weight-bold my-3">お届け先</h5>
           <div class="col-xs-10">
             <%= f.radio_button :my_address, "1", checked: true %>
             <%= f.label :"ご自身の住所"%><br>
             <%= "〒#{current_customer.postal_code} #{current_customer.address}"%><br>
             <%= "#{full_name(current_customer)}"%>
           </div>

          <% if @address != [] %>
          <div class="col-xs-10">
            <%= f.radio_button :my_address, "2"%>
             <%= f.label :"登録住所からの選択"%><br>
            <%= f.collection_select  :address_id, @addresses, :id, :order_address%>
          </div>
          <% end %>

           <div class="col-xs-10 mt-5">
             <%= f.radio_button :my_address, "3"%>
             <%= f.label :"新しいお届け先"%>
             <div class="col-xs-12 form_group">
               <%= f.label :"郵便番号（ハイフンなし）",class:"col-sm-4 form-control-static"%>
               <%= f.text_field :postal_code, class:"col-sm-3 form-control-static",placeholder:"0000000"%>
             </div>
             <div class="col-xs-12 form_group my-3">
               <%= f.label :"住所",class:"col-sm-4 form-control-static"%>
               <%= f.text_field :address, class:"col-sm-6 form-control-static",placeholder:"東京都渋谷区代々木神園町0-0",:size =>"100"%>
             </div>
             <div class="col-xs-12 form_group">
               <%= f.label :"宛名",class:"col-sm-4 form-control-static"%>
               <%= f.text_field :name, class:"col-sm-3 form-control-static",placeholder:"令和道子"%>
             </div>
           </div>

           <div class="col-xs-8 d-flex justify-content-center mt-5">
             <%= f.submit "確認画面へ進む", class:"btn btn-primary col-xs-5 "%>
           </div>
        <% end %>
        </div>
      <% else %>
        <p>お客様のカートに商品はありません。</p>
        <p><%= link_to "商品一覧", items_path, class:"btn btn-primary"%>から商品をお探し下さい。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/orders/show.html.erb
<% provide(:title, "注文履歴詳細") %>
<h2>注文履歴詳細</h2>
<% if @order.present? %>
<strong>注文情報</strong>
<table class="table table-bordered table-condensed">
  <tbody>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        <%= @order.postal_code %><br>
        <%= @order.address %><br>
        <%= @order.name %>
        </td>
    </tr>
    <tr>
      <th>支払い方法</th>
      <td><%= @order.payment_method %></td>
    </tr>
    <tr>
      <th>ステータス</th>
      <td><%= @order.status %></td>
    </tr>
  </tbody>
</table>
<strong>請求情報</strong>
<table class="table table-bordered table-condensed">
  <tr>
    <th>商品合計</th>
    <td><%= total_price(@order_details).to_s(:delimited) %>円</td>
  </tr>
  <tr>
    <th>配送料</th>
    <td><%= @order.shipping_cost.to_s(:delimited) %>円</td>
  </tr>
  <tr>
    <th>ご請求金額</th>
    <td><%= @order.total_payment.to_s(:delimited) %>円</td>
  </tr>
</table>
<strong>注文内容</strong>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>商品</th>
      <th>単価(税込)</th>
      <th>個数</th>
      <th>合計</th>
    </tr>
  </thead>
  <tbody>
    <% @order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item.name %></td>
      <td><%= order_detail.item.tax_in_price.to_s(:delimited) %>円</td>
      <td><%= order_detail.count %></td>
      <td><%= order_detail.tax_in_price.to_s(:delimited) %>円</td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "注文履歴一覧へ戻る", orders_path, class: "btn btn-info btn-lg order-index-back" %>
<% else %>
<p>注文履歴がありません</p>
<% end %>

app/views/customers/orders/thanx.html.erb
<div class="container">
  <div class="d-flex align-items-center justify-content-center" style="height:500px;">
    <h2>ご注文ありがとうございました</h2>
  </div>
</div>