config/routes.rb
Rails.application.routes.draw do
  #customer
  root to: "customers/homes#top"
  get 'about' => 'customers/homes#about'
  get '/customers/contact' => 'customers/customers#contact'

  devise_for :customers, :controllers => {:sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
  }
  scope module: :customers do
    resources :items,only:[:index, :show]
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'
    resource :customers,only:[:edit, :update, :show] do
      collection do
        get 'quit'
        patch 'out'
      end
    end

    resources :cart_items, only:[:index, :update, :create, :destroy] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
    resources :orders, only:[:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  #admin
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  get "/admin" => "admin/homes#index"

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :new, :create, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update] do
      member do
        get :current_index
        resource :order_details, only:[:update]
      end
      collection do
        get :today_order_index
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    validates :customer_id, :address, :name, :shipping_cost,
              :total_payment, :payment_method, presence: true
    validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
    validates :shipping_cost, :total_payment, numericality: { only_integer: true }

    enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
    enum status: {"入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中": 3, "発送済み": 4}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page]).per(10)
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    flash[:notice] = "注文ステータスを変更しました"
    redirect_to admin_order_path(@order)
      if @order.status == "入金確認"
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 1)
        end
      end
  end
  
  def today_order_index
  end

  def current_index
  end
  
  private
  def order_params
    params.require(:order).permit(:shipping_cost, :total_payment, :name, :payment_method, :address, :postal_code, :status, :making_status)
  end
  
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def new
    @order = Order.new
    @addresses = current_customer.addresses
  end

  def confirm
    @cart_items = current_customer.cart_items

    @order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method])

    # total_paymentに請求額を入れる billingはhelperで定義
    @order.total_payment = billing(@order)

    # my_addressに1が入っていれば（自宅）
    if params[:order][:my_address] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = full_name(current_customer)

    # my_addressに2が入っていれば（配送先一覧）
    elsif params[:order][:my_address] == "2"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address = ship.address
      @order.name = ship.name

    # my_addressに3が入っていれば(新配送先)
    elsif params[:order][:my_address] == "3"
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
      @ship = "1"

    # 有効かどうかの確認
      unless @order.valid? == true
        @addresses = Address.where(customer: current_customer)
        render :new
      end
    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    @order.save

    # 情報入力に新規配送先があれば保存
    if params[:order][:ship] =="1"
      current_customer.address.create(address_params)
    end

       # カート商品の情報を注文履歴に移動させる
    @cart_items = current_customer.cart_items
    @cart_items.each do |cart_item|
      @order_detail = OrderDetail.new
      @order_detail.item_id = cart_item.item_id
      @order_detail.order_id = @order.id
      @order_detail.count = cart_item.count
      @order_detail.price = cart_item.item.price * cart_item.count 
      @order_detail.save
      end
    # 最後にカートを全て削除する
    @cart_items.destroy_all

    redirect_to thanx_orders_path
  end

  def thanx
  end

  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_payment)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<% provide(:title, "注文一覧") %>

<div class="container">
  <h2 class="my-5">注文履歴一覧</h2>
  <table class="table">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td>
          <%= link_to admin_order_path(order) do %>
          <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
          <% end %>
        </td>
        <td><%= full_name(order.customer) %></td>
        <td><%= order.order_details.count %></td>
        <td><%= order.status %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate(@orders) %>
  </div>
  <div class="text-right">
    <%= link_to "トップページへ", admin_path, class:"btn btn-light" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<% provide(:title, "注文詳細") %>
<div class="container">
  <h2 class="my-5 text-center">注文履歴詳細</h2>
    <div class="row justify-content-center">
      <div class="col-xc-12">
        <table class="table table-borderless">
          <thead>
            <tr>
              <th>購入者</th>
              <th>注文日</th>
              <th>配送先</th>
              <th>支払い方法</th>
              <th>注文ステータス</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= full_name(@order.customer) %></td>
              <td><%= @order.created_at.strftime("%Y-%m-%d %H-%M-%S") %></td>
              <td>〒<%= full_address(@order) %></td>
              <td><%= @order.payment_method %></td>
              <td>
                <%= form_with(model: @order, url: admin_order_path, method: :patch, local: true) do |f| %>
                  <%= f.select :status, Order.statuses.keys, class:"status" %>
                  <%= f.submit "更新", class: "btn btn-sm btn-success" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-xs-8">
        <table class="table table-bordered">
          <thead class="thead-light">
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>制作ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.item.tax_in_price %></td>
              <td><%= order_detail.count %></td>
              <td><%= sub_price(order_detail) %></td>
              <td>
                <%= form_with(model: order_detail, url: admin_order_details_path(order_detail.id), method: :patch, local:true) do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys, class:"making_status" %>
                  <%= f.submit "更新", class:"btn btn-success" %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="col-xs-3 off-set-1">
          <table class="table">
            <thead>
              <tr>
                <th>送料</th>
                <th>商品合計</th>
                <th>請求金額</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="text-right col-xs-5">
                  ¥<%= @order.shipping_cost %>
                </td>
                <td class="text-right col-xs-5">
                  ¥<%= total_price(@order.order_details) %>
                </td>
                <td class="text-right col-xs-5">
                  ¥<%= total_price(@order.order_details) + @order.shipping_cost %>
                </td>
              </tr>
              <tr>
                <th></th>
                <td class="text-right col-xs-5">
                  <%= link_to "注文履歴へ戻る", admin_orders_path, class: "btn btn-outline-secondary" %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>