config/routes.rb
Rails.application.routes.draw do
  #customer
  root to: "customers/homes#top"
  get 'about' => 'customers/homes#about'
  get '/customers/contact' => 'customers/customers#contact'

  devise_for :customers, :controllers => {:sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
  }
  scope module: :customers do
    resources :items,only:[:index, :show]
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'
    resource :customers,only:[:edit, :update, :show] do
      collection do
        get 'quit'
        patch 'out'
      end
    end

    resources :cart_items, only:[:index, :update, :create, :destroy] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
    resources :orders, only:[:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'thanx'
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  #admin
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  get "/admin" => "admin/homes#index"

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :new, :create, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update] do
      member do
        get :current_index
        resource :order_details, only:[:update]
      end
      collection do
        get :today_order_index
      end
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
     @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
		if @genre.save
		   @genres = Genre.all
		  # redirect_to admin_genres_path
		else
		  @genres = Genre.all
		  render :index
		end

  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "変更内容を更新しました。"
      redirect_to admin_genres_path
    else
      flash[:alert] = "変更内容に不備があります。"
      render "edit"
    end
  end

  private

	def genre_params
	  params.require(:genre).permit(:name)
	end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_genre_new.html.erb
<% genre.each do |genre| %>
<tr>
  <td><%= genre.name %></td>
  <td><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success py-0" %></td>
</tr>
<% end %>

app/views/admin/genres/create.js.erb
$("#genre_index_new").html("<%= escape_javascript(render 'genre_new', genre: @genres) %>")
$('#form').val('');

app/views/admin/genres/edit.html.erb
<% provide(:title, "ジャンル編集") %>

<div class="container mt-5 md-5">
  <div class="row">
    <div class="col">
      <h2 class="text-center">ジャンル編集</h2>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-5">
      <%= form_with model: @genre, url: admin_genre_path, method: :patch, local: true do |f| %>
      <div class="form-group">
        <%= f.label "ジャンル名", class:"form-label" %>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="col-md justify-content-around" >
        <%= f.submit "変更を保存", class:"btn btn-success my-3 mr-3" %>
        <%= link_to "ジャンル一覧へ戻る", admin_genres_path, class:"btn btn-outline-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<% provide(:title, "ジャンル一覧") %>

<div class="container">
  <div class="row text-center">
    <div class="col-md-12 mt-5">
      <h2>ジャンル一覧・追加</h2>
    </div>
  </div>
  </br>
  <div class="row y-5 d-flex justify-content-center">
    <div class="col-xs-12">
      <%= form_with model: @genre, url: admin_genres_path, method: :post, remote: true do |f| %>
        <%= f.label :name, "ジャンル名" %>
        <%= f.text_field :name, id: "form" %>
        <%= f.submit "追加する", class:"btn btn-success ml-4 py-1" %>
      <% end %>
    </div>
  </div>
  <div class="row mt-5 justify-content-center">
    <table class="col-lg-5 mt-3">
      <thead>
        <tr>
          <th>登録ジャンル名</th>
          <th></th>
        </tr>
        <td></td>
      </thead>
      <tbody id="genre_index_new">
        <%= render "genre_new", genre: @genres %>
      </tbody>
    </table>
  </div>
  <div class="text-right">
    <%= link_to "トップページへ", admin_path, class:"btn btn-light" %>
  </div>
</div>